// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbBlWuZ3R4McZ2zyWdLjHDv0dfZLla_fI',
    appId: '1:219823823001:android:511ddddd6d6e0d7efb8008',
    messagingSenderId: '219823823001',
    projectId: 'haru-9a509',
    databaseURL: 'https://haru-9a509-default-rtdb.firebaseio.com',
    storageBucket: 'haru-9a509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9dJ5ks5fdlFMGLjn-zRKO1hWdS2DtkT0',
    appId: '1:219823823001:ios:9e20df2cd15d3a5bfb8008',
    messagingSenderId: '219823823001',
    projectId: 'haru-9a509',
    databaseURL: 'https://haru-9a509-default-rtdb.firebaseio.com',
    storageBucket: 'haru-9a509.appspot.com',
    iosClientId: '219823823001-45ofbp8vrtu3dflgitduveh3s1d5ged9.apps.googleusercontent.com',
    iosBundleId: 'com.example.haru',
  );
}
